logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        orm:
          jdbc:
            bind: TRACE
server:
  port: 8080
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: g1e2i3o4r5g6@
    url: jdbc:mysql://scores-pe-db-new.mysql.database.azure.com:3306/pe_scores?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=true&requireSSL=false
#    url: jdbc:mysql://localhost:3306/pe_scores?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: scoresPe

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  mvc:
    hidden-method:
      filter:
        enabled: true
  sql:
    init:
      mode: always

  hostName: https://pescores.azurewebsites.net/